version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp/client:${BUILD_ID}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL=http://localhost:5001

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp/server:${BUILD_ID}
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb+srv://anas:tSUrDdvOGGhzKE2J@cluster0.tpi9ehl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=StringHardToGuessForSecurity
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
